# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [issa, NWO]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username hunters.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username mouse3687
issuehunt: # Replace with a single IssueHunt username foxtrot
otechie: # Replace with a single Otechie username WIKIS
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://sans.org','https://idgo.com','https://Fans.starl.ink','https://fema.gov','https://pornhub.com','https://dhs.gov/Coronavirus.org','https://knightlinelegal.com','https://livelinks.com','https://ambers.org','https://marchofdimes.org','https://soforeverloved.com/busy/','https://Voodoo.io']
